# Welcome

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,27,7,8], np.int8) # -128 to 127

In [3]:
myarr

array([ 3, 27,  7,  8], dtype=int8)

In [4]:
myarr[0]

3

In [5]:
myarr = np.array([[3,27,7,8]], np.int8) # -128 to 127

In [6]:
myarr[0][1]

27

In [7]:
myarr.dtype

dtype('int8')

In [8]:
myarr[0][1] = 30   

In [9]:
myarr

array([[ 3, 30,  7,  8]], dtype=int8)

# Array creation : Conversion from other python structures

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int64')

In [14]:
listarray.size

9

In [15]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [16]:
zeros =  np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
 rng = np.arange(5)

In [22]:
rng

array([0, 1, 2, 3, 4])

In [24]:
rng[2]

2

In [29]:
lspace = np.linspace(1,5,4) # four elements between 1 to 5 including

In [30]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [37]:
emp = np.empty((4,6))

In [38]:
emp

array([[2.31584178e+077, 2.31584178e+077, 6.42285340e-323,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.14700246e-314, 0.00000000e+000],
       [2.14696782e-314, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [40]:
emp_like = np.empty_like(lspace)

In [41]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [42]:
ide = np.identity(45)

In [43]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [44]:
ide.shape

(45, 45)

In [45]:
arr = np.arange(99)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr = arr.reshape(3,33)

In [53]:
#arr.reshape(3,34) error

In [54]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [60]:
arr = arr.ravel()# convert into 1D array

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [62]:
arr.shape

(99,)

In [63]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [67]:
ar = np.array(x)

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar.sum(axis=0) 

array([12,  8,  9])

In [71]:
ar.sum(axis=1) 

array([ 6, 15,  8])

In [72]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [73]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [74]:
 ar.ndim

2

In [75]:
ar.size

9

In [76]:
ar.nbytes

72

In [77]:
 ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [78]:
ar.argmax()

6

In [79]:
ar.argmin()


8

In [80]:
ar.argmax(axis=0)

array([2, 1, 1])

In [81]:
ar.argmax(axis=1)

array([2, 2, 0])

In [82]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [83]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [86]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [94]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [95]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [96]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [97]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [101]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [102]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [103]:
ar.sum()

29

In [104]:
ar.max()

7

In [106]:
ar.min()

0

In [107]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [108]:
np.count_nonzero(ar)

8

In [110]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [113]:
ar[1,2] = 0

In [114]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [121]:
import sys

In [122]:
py_ar = [1,2,3,4]

In [123]:
np_ar = np.array(py_ar)

In [129]:
sys.getsizeof(1) * len(py_ar)  

112

In [132]:
np_ar.itemsize * np_ar.size

32

In [134]:
np_ar.tolist()

[1, 2, 3, 4]